   <?php      
   
   echo $this->headLink()
                        ->prependStylesheet($this->basePath('css/normalize.css'))
                        ->prependStylesheet($this->basePath('css/jquery.steps.css'))
                        ->prependStylesheet($this->basePath('css/parsley.css'));
                    	
?>


<style type="text/css" media="screen">
		/*custom font*/
@import url(http://fonts.googleapis.com/css?family=Montserrat);

/*basic reset*/
* {margin: 0; padding: 0;}


body {
	font-family: montserrat, arial, verdana;
}
/*form styles*/
#wizard {
	margin: 0px auto;
	text-align: center;
	position: relative;
}


/*inputs*/

/*buttons*/

#wizard .action-button:hover, #wizard .action-button:focus {
	box-shadow: 0 0 0 2px white, 0 0 0 3px #27AE60;
}

#wizard .scroll{
	height:400px;
	overflow:auto;
	overflow-x:hidden;
}

      .validate {
        margin-top: 10px;
      }
   
      .invalid-form-error-message {
        margin-top: 10px;
        padding: 5px;
      }
      .invalid-form-error-message.filled {
        border-left: 2px solid red;
      }
      .btn-info, .btn-default {
        margin-top: 10px;
      }


#wizard input,select,textarea {
	padding: 15px;
	border: 1px solid #ccc;
	border-radius: 3px;
	margin-bottom: 10px;
	width: 100%;
	box-sizing: border-box;
	font-family: montserrat;
	color: #2C3E50;
	font-size: 13px;
}

	
		</style>

<?php
echo $this->headScript()
            ->prependFile($this->basePath('js/modernizr-2.6.2.min.js'))
            ->prependFile($this->basePath('js/jquery.cookie-1.3.1.js'))
            ->prependFile($this->basePath('js/jquery.steps.js'))
            ->prependFile($this->basePath('js/parsley.min.js'))
 			->prependFile($this->basePath('js/pt-br.js'));
 			
 		

 // module/Cliente/view/cliente/cliente/add.phtml:

 $title = 'Adicionar Cliente';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('cliente', array('action' => 'add')));
 $form->prepare();



 echo $this->formHidden($form->get('id'));



 //exibe o formulario carregado do controller
 #echo $this->formCollection($form);
 ?>

            <script>
            	
                $(function ()
                {

                    $("#wizard").steps({
                        headerTag: "h2",
                        bodyTag: "section",
                        transitionEffect: "slideLeft"
                    });

                   
                });


            </script>

            <form id="form" method="post" action="teste.php" data-parsley-validate>

            <div class="main">

            <div id="wizard" class="col-md-12">
                <h2>Dados Pessoais</h2>

                <section class="scroll">

                <div class="row">
		                <div class="col-md-6">
		               		<input type="text" name="nome" data-parsley-pattern="/^[(]{0,1}[0-9]{2,3}[)]{0,1}[-\s\.]{0,1}[0-9]{4,5}[-\s\.]{0,1}[0-9]{4}$/" placeholder="NOME" value="" required data-parsley-group="block1">
		                </div>
		                
		                <div class="col-md-6">
		                	<input type="text" 	 name="contato" placeholder="CONTATO" required data-parsley-minlength="3" data-parsley-maxlength="20"   data-parsley-minlength-message = "No mínimo 3 caracteres!" data-parsley-maxlength-message = "No máximo 20 caracteres!" data-parsley-group="block1">
		                </div>
						
						<div class="col-md-6">
		                	<input type="text" name="cep" data-parsley-trigger="keyup" data-parsley-pattern="/^[0-9]{5}-[0-9]{3}$/" placeholder="CEP"  data-parsley-cep-message="CEP inválido	" value="" required data-parsley-group="block1">
		                </div>

                </div>

                  <div class="row">
		                 <div class="col-md-6">
		               		<?php  echo $this->formRow($form->get('estado')); ?>
						</div>
		                
		                <div class="col-md-6">
		               		<select name="cidade">
								<option value="">SELECIONE O ESTADO</option>
		               		</select>
		                </div>
                </div>

                 <div class="row">
		                <div class="col-md-6">
			                <input type="text" name="bairro" placeholder="BAIRRO" value="">
			            </div>
		                
		                <div class="col-md-6">
		                     <input type="text" name="logradouro" placeholder="LOGRADOURO" value="">
		                </div>
                </div>

                <div class="row">
		                <div class="col-md-6">
		               		<input type="text" name="numero" placeholder="NUMERO" value="">
		                </div>
		                
		                <div class="col-md-6">
		                		<input type="text" name="complemento" placeholder="COMPLEMENTO" value="">
		                </div>
                </div>
                <div class="row">
		                <div class="col-md-6">
		               		<input type="text" name="profissao" placeholder="PROFISSÃO" value="">
		                </div>
		                
		                <div class="col-md-6">
		                		<input type="text" name="setor" placeholder="SETOR" value="">
		                </div>
                </div>

                <div class="row">
		                <div class="col-md-6">
		               		<input type="text" name="cpf" placeholder="CPF" value="">
		                </div>
		                
		                <div class="col-md-6">
		                		<input type="text" name="rg" placeholder="RG" value="">
		                </div>
                </div>

                <div class="row">
		                <div class="col-md-6">
		               		<input type="text" name="email" placeholder="EMAIL" value="">
		                </div>
		                
		                <div class="col-md-6">
		                		<input type="text" name="data_nasc" placeholder="DATA NASCIMENTO" value="">
		                </div>
                </div>

                 <div class="row">
		                <div class="col-md-6">
		               		<input type="text" name="telefone" placeholder="TELEFONE" value="">
		                </div>
		                
		                <div class="col-md-6">
		                		<input type="text" name="celular" placeholder="CELULAR" value="">
		                </div>
                </div>

               


				</section>

                <h2> Cliente</h2>
                <section class="scroll">

                 <div class="row">
		                <div class="col-md-6">
		               		<select name="tipo_pessoa">
								<option value="">TIPO PESSOA</option>
		               			<option value="0">Física</option>
		               			<option value="1">Jurídica</option>
		               			</select>
		                </div>
		                
		                <div class="col-md-6">
		                		&nbsp;
		                </div>
                </div>


                 <div class="row">
		                <div class="col-md-6">
		               		<input type="text" name="ramo" placeholder="RAMO" value="">
		                </div>
		                
		                <div class="col-md-6">
		                		<input type="text" name="cnpj" placeholder="CNPJ" value="">
		                </div>
                </div>

                <div class="row">
		                <div class="col-md-6">
		               		<input type="text" name="site" placeholder="SITE" value="">
		                </div>
		                
		                <div class="col-md-6">
		                		<input type="text" name="setor" placeholder="CNPJ" value="">
		                </div>
                </div>

                 <div class="row">
		                <div class="col-md-6">
		               		<input type="text" name="cep2" data-parsley-range="[8, 40]" placeholder="CEP" value=""  required data-parsley-group="block2">
		                </div>
		                
		                <div class="col-md-6">
		                		&nbsp;
		                </div>
                </div>

                
				<div class="row">
		                <div class="col-md-6">
		               		<select name="indicacao">
								<option value="">INDICAÇÃO</option>
		               			<option value="cartao">Cartao</option>
		               			<option value="cliente">Cliente</option>
		               			<option value="google">Google</option>
		               			<option value="facebook">Facebook</option>
		               			<option value="vendedor">Vendedor</option>
		               			
		               			<option value="outros">Outros</option>
		               		</select>
		                </div>
		                
		                <div class="col-md-6">
		                		<input type="text" name="outros_indicacao" placeholder="Outros" value="">
		                </div>
                </div>

                  <div class="row">
		                <div class="col-md-6">
		               		<select name="vendedor">
								<option value="">VENDEDOR</option>
		               			<option value="0">ARTHUR</option>
		               			</select>
		                </div>
		                
		                <div class="col-md-6">
		                		&nbsp;
		                </div>
                </div>

                </section>

                <h2>Serviços</h2>
                <section>
                    <p>Morbi ornare tellus at elit ultrices id dignissim lorem elementum. Sed eget nisl at justo condimentum dapibus. Fusce eros justo, 
                        pellentesque non euismod ac, rutrum sed quam. Ut non mi tortor. Vestibulum eleifend varius ullamcorper. Aliquam erat volutpat. 
                        Donec diam massa, porta vel dictum sit amet, iaculis ac massa. Sed elementum dui commodo lectus sollicitudin in auctor mauris 
                        venenatis.</p>
                </section>

                <h2>Pagamento</h2>
                <section>
                    <p>Quisque at sem turpis, id sagittis diam. Suspendisse malesuada eros posuere mauris vehicula vulputate. Aliquam sed sem tortor. 
                        Quisque sed felis ut mauris feugiat iaculis nec ac lectus. Sed consequat vestibulum purus, imperdiet varius est pellentesque vitae. 
                        Suspendisse consequat cursus eros, vitae tempus enim euismod non. Nullam ut commodo tortor.</p>
                </section>
                 <div class="invalid-form-error-message"></div>
            </div>
</div>
<?php  echo $this->form()->closeTag(); ?>


 <script type="text/javascript">

  window.ParsleyValidator.setLocale('pt-br');


	var estado;
	var cidade;
	var bairro;
	var logradouro;

	var urlcidade = "/cidade/buscaporestado/"; 

	//Funcao para pegar endereco de acordo com o CEP


	function Endereco()
	{	

		var field_uf;
		var namefield_uf;

		var field_cidade;
		var namefield_cidade;

		var field_bairro;
		var namefield_bairro;

		var field_logradouro;
		var namefield_logradouro;

		this.cep; 

		this.getCep = function () { 
			return this.cep; 
		};
		 this.setCep = function (value) { 
		 	this.cep = $.trim(value); 
		 }; 
		
		this.getUf = function () { 
			return field_uf; 
		};

		this.setUf = function (value) { 
		 	field_uf = $.trim(value);  
		}; 

		this.getNameFieldUf = function () { 
			return namefield_uf; 
		};
		
		this.setNameFieldUf = function (value) { 
		 	namefield_uf = $.trim(value);  
		}; 

		this.getCidade = function () { 
			return field_cidade; 
		};
		this.setCidade = function (value) { 
		 	field_cidade = $.trim(value);  
		};

		this.getNameFieldCidade = function () { 
			return namefield_cidade; 
		};
		
		this.setNameFieldCidade = function (value) { 
		 	namefield_cidade = $.trim(value);  
		}; 

		this.getBairro = function () { 
			return field_bairro; 
		};
		this.setBairro = function (value) { 
		 	field_bairro = $.trim(value);  
		};

		this.getNameFieldBairro = function () { 
			return namefield_bairro; 
		};
		
		this.setNameFieldBairro= function (value) { 
		 	namefield_bairro = $.trim(value);  
		}; 

		this.getLogradouro = function () { 
			return field_logradouro; 
		};
		this.setLogradouro = function (value) { 
		 	field_logradouro = $.trim(value); 
		};

		this.getNameFieldLogradouro = function () { 
			return namefield_logradouro; 
		};
		
		this.setNameFieldLogradouro= function (value) { 
		 	namefield_logradouro = $.trim(value);  
		}; 



	}


	Endereco.prototype.estado = function(estadouf,cidadeselect,cidadeField)
	{
		
		 var optionestado;
		 var estadochecked 	= false;
		 
		 estadouf 			= estadouf.toLowerCase();
		 var campo 			= this.getNameFieldUf();
		 var idestado 		= null;

	

		 //console.log(this.getCidade)
		 //this.setNameFieldUf
		 $(campo+' option').filter(function () { 
		 	
		 	optionestado 	= $.trim($(this).html()).toLowerCase();
		 	
		 	if(optionestado == estadouf && estadochecked === false)
		 	{

		 		estadochecked = true;
				$(this).prop('selected', true);

				 idestado = $(this).attr('value');

				 var classeEndereco		 = new Endereco();
				 classeEndereco.cidade(idestado,cidadeselect,cidadeField);
		 	}
		 	

		  });

	 }

	 Endereco.prototype.cidade = function(id,nomecidade,campo)
	{

		
		urlcidade += id;

	

		var cidadechecked 	= false;
		
		var cidadeoption 	= '';
		
		$.getJSON(urlcidade, function( cidades ) {


			$(campo).eq(0).text('');
			$(campo).eq(0).append('<option value="">SELECIONE A CIDADE</option>');

			$.each(cidades, function(index,cidadeobj){

				if (cidadeobj instanceof Object == true) {

						if(cidadeobj.id.length > 0 && cidadeobj.cidade.length > 0)
						{

							cidadeoption = cidadeobj.cidade;
							cidadeoption = cidadeoption.toUpperCase();

							//formar options

							$(campo).append($('<option>', {
			    				value: cidadeobj.id,
			    				text: cidadeoption
							}));
							
							
							
						}

				}
				else
					$(campo).html();

			});

			if($.trim(nomecidade) != '')
			{

				$(campo+' option').filter(function () { 
			 	
			 	var optionecidade 	= $.trim($(this).html()).toUpperCase();

			 	nomecidade 			= nomecidade.toUpperCase();
			 	
			 	if(optionecidade == nomecidade && cidadechecked === false)
			 	{
			 		cidadechecked = true;
					$(this).prop('selected', true);

					
			 	}
			 	

			  });
			}

		}); //close JSON

  

	 }


	Endereco.prototype.logradouro = function()
	{
		
		 var campo 			= this.getNameFieldLogradouro();
		 $(campo).val(this.getLogradouro());

	 }

	Endereco.prototype.bairro = function()
	{
		
		 var campo 			= this.getNameFieldBairro();

		 $(campo).val(this.getBairro());

	}



	

  $(function (){

  	 var oldcep;
  	 var tempValue;

 	 var classeEnd		 = new Endereco();
  	 //var classeEnd2 	 = new Endereco();

  	 classeEnd.setNameFieldUf('select[name="estado"]');
  	 classeEnd.setNameFieldCidade('select[name="cidade"]');
  	 classeEnd.setNameFieldBairro('input[name="bairro"]');
  	 classeEnd.setNameFieldLogradouro('input[name="logradouro"]');

  	 var fieldEstado = classeEnd.getNameFieldUf();


  		 $('input[name="cep"]').bind('focusout',function (){

  		 	tempValue 	= $.trim($('input[name="cep"]').val());
		
			 
		 	 var url 	= "/cep/"+tempValue; //MANEIRA CORRETA

		 	
		 	 oldcep 	= $.trim(classeEnd.getCep());
		 	
		 	 // Compara os valores do CEP
		 	if(oldcep != tempValue)
		 	{
		 	 	//JSON
		 	 	$.getJSON(url, function( cep ) {
			  		//verificar se é objeto
			   		if (cep instanceof Object == true) {

						if(cep.bairro.length > 0 && cep.logradouro.length > 0  && cep.localidade.length > 0  && cep.uf.length > 0)
						{
							//set Valor do CEP
					 		classeEnd.setCep(tempValue);
					 		classeEnd.setUf(cep.uf);
					 		
					 		classeEnd.setCidade(cep.localidade);
					 		
					 		classeEnd.setBairro(cep.bairro);
					 		
					 		classeEnd.setLogradouro(cep.logradouro);
					 		
					 		//  camposCep.prototype = new Cep();
					 		var estadouf 	   = classeEnd.getUf();
					 		var cidadeselect   = classeEnd.getCidade();
	 	 					var cidadeField    = classeEnd.getNameFieldCidade();
					 		
					 		classeEnd.estado(estadouf,cidadeselect,cidadeField);
					 		classeEnd.bairro();
					 		classeEnd.logradouro();

					 	}
				 	
					}
							 
		 		});	//close getJson
		 	 }
		 	 	
		}); // close bind 

   		var estadotext = '';


   		$(fieldEstado).change(function(){

   			estadotext =  $(fieldEstado+' option:selected').text();
   			
   			classeEnd.setUf(estadotext);

   			cidadeField    = classeEnd.getNameFieldCidade();

   			classeEnd.estado(estadotext,'',cidadeField);

   		})


  });//close Jquery



 </script>