<?php
 // module/Tarefas/view/tarefas/tarefas/index.phtml:

 $title = 'Minhas tarefas';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
  <table class="table">
     <tr>
         <th>Titulo</th>
         <th>Responsavel</th>
         <th>Prioridade</th>
         <th>&nbsp;</th>
     </tr>
     <?php foreach ($this->paginator as $tarefas) : // <-- change here! ?>
         <tr>
             <td><?php echo $this->escapeHtml($tarefas->titulo);?></td>
             <td><?php echo $this->escapeHtml($tarefas->fk_responsavel);?></td>
             <td>
                 <a href="<?php echo $this->url('tarefas',
                     array('action' => 'edit', 'id' => $tarefas->id));?>">Edit</a>
                 <a href="<?php echo $this->url('tarefas',
                     array('action' => 'delete', 'id' => $tarefas->id));?>">Delete</a>
             </td>
         </tr>
     <?php endforeach; ?>
 </table>
  <?php
 // add at the end of the file after the table
    echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => 'tarefas'
     )
 );
 ?>